# Generated by Django 3.0 on 2020-05-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
