# Generated by Django 3.0 on 2020-05-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
